### ISSUE TITLE
Dev environment not working with node v17.1.0

### ISSUE THREAD

**Issue by secondl1ght** [getAlby/lightning-browser-extension#428]
When running the `yarn run dev:chrome` command and using Node version 17.1.0, I get the following output:

```
yarn run v1.22.17
$ cross-env NODE_ENV=development cross-env TARGET_BROWSER=chrome webpack --watch
node:internal/crypto/hash:67
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at BulkUpdateDecorator.hashFactory (/home/mk/Desktop/CODE/alby-redesign-new/node_modules/webpack/lib/util/createHash.js:155:18)
    at BulkUpdateDecorator.digest (/home/mk/Desktop/CODE/alby-redesign-new/node_modules/webpack/lib/util/createHash.js:80:21)
    at /home/mk/Desktop/CODE/alby-redesign-new/node_modules/webpack/lib/DefinePlugin.js:595:38
    at Hook.eval [as call] (eval at create (/home/mk/Desktop/CODE/alby-redesign-new/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:104:1)
    at Hook.CALL_DELEGATE [as _call] (/home/mk/Desktop/CODE/alby-redesign-new/node_modules/webpack/node_modules/tapable/lib/Hook.js:14:14)
    at Compiler.newCompilation (/home/mk/Desktop/CODE/alby-redesign-new/node_modules/webpack/lib/Compiler.js:1053:26)
    at /home/mk/Desktop/CODE/alby-redesign-new/node_modules/webpack/lib/Compiler.js:1097:29
    at Hook.eval [as callAsync] (eval at create (/home/mk/Desktop/CODE/alby-redesign-new/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v17.1.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by secondl1ght** [comment]
FYI I am getting this same error with a different React application so this may be a Node and React issue.

**Comment by escapedcat** [comment]
This might be helpful:  
https://stackoverflow.com/questions/69692842/error-message-error0308010cdigital-envelope-routinesunsupported  

This seems to explain it:  
> node.js 17 uses OpenSSL3 which have changed code for initialization context of md family (including md4):

https://github.com/webpack/webpack/issues/14532#issuecomment-947807590  
There's more suggestions in that issue on how to deal with this.

**Comment by MoritzKa** [comment]
is it working now?

**Comment by escapedcat** [comment]
Looks good on latest stable v18:  
```sh
master  nvm install 18
v18.7.0 is already installed.
Now using node v18.7.0 (npm v8.15.0)

master  yarn
yarn install v1.22.19
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
success Already up-to-date.
$ husky install
husky - Git hooks installed
✨  Done in 1.82s.

master  yarn run dev:chrome
yarn run v1.22.19
$ cross-env NODE_ENV=development TARGET_BROWSER=chrome webpack --watch
wext-manifest-webpack-plugin: removed js/manifest.bundle.js
(node:72712) [DEP_WEBPACK_CHUNK_HAS_ENTRY_MODULE] DeprecationWarning: Chunk.hasEntryModule: Use new ChunkGraph API
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:72712) [DEP_WEBPACK_CHUNK_ENTRY_MODULE] DeprecationWarning: Chunk.entryModule: Use new ChunkGraph API
(node:72712) [DEP_WEBPACK_DEPRECATION_ARRAY_TO_SET] DeprecationWarning: chunk.files was changed from Array to Set (using Array method 'filter' is deprecated)
```

Uneven node versions are usually "testing" versions. Only even versions are maintained releases. See:

![image](https://user-images.githubusercontent.com/1016218/185772849-f04d2653-2425-4a9c-a9d3-56685c61b1c3.png)
https://nodejs.org/en/about/releases/

We should switch to 16 or 18 by now. Can be done in a new issue: #1314
