### ISSUE TITLE
AccountMenu Test warning: "Warning: An update to Menu inside a test was not wrapped in act(...)"

### ISSUE THREAD

**Issue by bumi** [getAlby/lightning-browser-extension#998]
### Describe the bug

The `AccountMenu` test logs the following error/warning.
https://github.com/getAlby/lightning-browser-extension/blob/master/src/app/components/AccountMenu/index.test.tsx#L65-L79

```
  console.error
    Warning: An update to Menu inside a test was not wrapped in act(...).

    When testing, code that causes React state updates should be wrapped into act(...):

    act(() => {
      /* fire events that update state */
    });
    /* assert on the output */

    This ensures that you're testing the behavior the user would see in the browser. Learn more at https://reactjs.org/link/wrap-tests-with-act
        at Menu (lightning/lightning-browser-extension/node_modules/@headlessui/react/dist/headlessui.dev.cjs:3176:50)
        at div
        at title (lightning/lightning-browser-extension/src/app/components/AccountMenu/index.tsx:22:24)
        at basename (lightning/packages/react-router/lib/components.tsx:173:3)
        at basename (lightning/packages/react-router-dom/index.tsx:147:3)
```

### To Reproduce

run `jest`

### Alby information

- Alby Version: master

### Device information [optional]:

- OS: maxOS
- Browser tests

### Are you working on this issue?
NO

**Comment by bumi** [comment]
solved in: https://github.com/getAlby/lightning-browser-extension/commit/d7825cceff3f0f94bc54f26a3a446722c73507af
